# Tensors Variables and Placeholders

### Tensor is multidimensional array.

In [1]:
import tensorflow as tf

D:\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
scalar = tf.constant(3)
vector = tf.constant([3, 4, 5, 6])
matrix = tf.constant([[3, 5], [9, 10]])
tensor = tf.constant([[[3, 5], [9, 10]], [[7, 5], [1, 10]]])

matrix2 = tf.constant([[7, 1], [3, 10]])

with tf.Session() as session:
    result = session.run(scalar)
    print("Scalar:\n", result)
    result = session.run(vector)
    print("Vector:\n", result)
    result = session.run(matrix)
    print("Matrix:\n", result)
    result = session.run(tensor)
    print("Tensor:\n", result)

Scalar:
 3
Vector:
 [3 4 5 6]
Matrix:
 [[ 3  5]
 [ 9 10]]
Tensor:
 [[[ 3  5]
  [ 9 10]]

 [[ 7  5]
  [ 1 10]]]


## Operations with matrices

In [3]:
matrix2 = matrix * 2

with tf.Session() as session:
    result = session.run(matrix2)
    print("Multiply matrix by 2:\n", result)

Multiply matrix by 2:
 [[ 6 10]
 [18 20]]


In [4]:
result_adding_matrices = matrix + matrix2

with tf.Session() as session:
    matrix1 = session.run(matrix)
    matrix2 = session.run(matrix2)
    result = session.run(result_adding_matrices)
    
    print(matrix1)
    print("+")
    print(matrix2)
    print("-" * 10)
    print(result)

[[ 3  5]
 [ 9 10]]
+
[[ 6 10]
 [18 20]]
----------
[[ 9 15]
 [27 30]]


## Variables

### Simple counter.

In [5]:
state = tf.Variable(0)
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)
init_op = tf.variables_initializer([state])
print("Counter:")
with tf.Session() as session:
    session.run(init_op)
    print(session.run(state))
    for _ in range(5):
        session.run(update)
        print(session.run(state))

Counter:
0
1
2
3
4
5


## Placeholders

### Feed data to TensorFlow from outside a model. Placeholder is likevariable that will not actually receive its data until a later point.

In [6]:
a = tf.placeholder(tf.float32)
b = a * 2

with tf.Session() as session:
    result = session.run(b, feed_dict={a: 6.5})
    print("Placeholder {a: 6.5}:", result)

dictionary = {a: [[[3, 5], [9, 10]], [[7, 5], [1, 10]]]}
with tf.Session() as session:
    result = session.run(b, feed_dict=dictionary)
    print("Placeholder {a: [[[3, 5], [9, 10]], [[7, 5], [1, 10]]]}:\n", result)

Placeholder {a: 6.5}: 13.0
Placeholder {a: [[[3, 5], [9, 10]], [[7, 5], [1, 10]]]}:
 [[[ 6. 10.]
  [18. 20.]]

 [[14. 10.]
  [ 2. 20.]]]
